pub mod hspace;
mod niri;
pub mod paymo;
pub mod pulseaudio;
pub mod system;
pub mod test_display;
pub mod time;
pub mod tray;
pub mod weather;
pub mod weather_icons;
pub mod windows;
pub mod workspaces;
